---
- name: Check if Prometheus directory exists
  stat:
    path: /opt/prometheus
  register: prometheus_dir

- name: Download Prometheus
  command: >
    wget https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz
  args:
    chdir: /tmp
  when: prometheus_dir.stat.exists == false

- name: Extract Prometheus
  command: tar xvfz prometheus-2.30.0.linux-amd64.tar.gz
  args:
    chdir: /tmp
  when: prometheus_dir.stat.exists == false

- name: Move Prometheus to /opt directory
  command: mv /tmp/prometheus-2.30.0.linux-amd64 /opt/prometheus
  args:
    creates: /opt/prometheus
  when: prometheus_dir.stat.exists == false

- name: Create Prometheus configuration file
  copy:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
      # Add more scrape configurations as needed
    dest: /opt/prometheus/prometheus.yml

- name: Create Prometheus service file
  copy:
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml
      User=nobody
      Restart=always

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started
